champion_masteries_example = [
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 145,
        "championLevel": 5,
        "championPoints": 68336,
        "lastPlayTime": 1683647151000,
        "championPointsSinceLastLevel": 46736,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 81,
        "championLevel": 5,
        "championPoints": 56467,
        "lastPlayTime": 1687090778000,
        "championPointsSinceLastLevel": 34867,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 51,
        "championLevel": 5,
        "championPoints": 49793,
        "lastPlayTime": 1682245436000,
        "championPointsSinceLastLevel": 28193,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 119,
        "championLevel": 5,
        "championPoints": 49552,
        "lastPlayTime": 1684681264000,
        "championPointsSinceLastLevel": 27952,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 236,
        "championLevel": 5,
        "championPoints": 36891,
        "lastPlayTime": 1682362093000,
        "championPointsSinceLastLevel": 15291,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 498,
        "championLevel": 5,
        "championPoints": 31331,
        "lastPlayTime": 1685039899000,
        "championPointsSinceLastLevel": 9731,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 202,
        "championLevel": 5,
        "championPoints": 29490,
        "lastPlayTime": 1684779862000,
        "championPointsSinceLastLevel": 7890,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 2,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 222,
        "championLevel": 5,
        "championPoints": 26175,
        "lastPlayTime": 1684627156000,
        "championPointsSinceLastLevel": 4575,
        "championPointsUntilNextLevel": 0,
        "chestGranted": True,
        "tokensEarned": 1,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 523,
        "championLevel": 3,
        "championPoints": 11911,
        "lastPlayTime": 1685033714000,
        "championPointsSinceLastLevel": 5911,
        "championPointsUntilNextLevel": 689,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 45,
        "championLevel": 3,
        "championPoints": 9241,
        "lastPlayTime": 1684603417000,
        "championPointsSinceLastLevel": 3241,
        "championPointsUntilNextLevel": 3359,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 221,
        "championLevel": 3,
        "championPoints": 8530,
        "lastPlayTime": 1681130163000,
        "championPointsSinceLastLevel": 2530,
        "championPointsUntilNextLevel": 4070,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 18,
        "championLevel": 3,
        "championPoints": 8507,
        "lastPlayTime": 1682011022000,
        "championPointsSinceLastLevel": 2507,
        "championPointsUntilNextLevel": 4093,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 96,
        "championLevel": 3,
        "championPoints": 7776,
        "lastPlayTime": 1684515690000,
        "championPointsSinceLastLevel": 1776,
        "championPointsUntilNextLevel": 4824,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 110,
        "championLevel": 3,
        "championPoints": 6217,
        "lastPlayTime": 1680626083000,
        "championPointsSinceLastLevel": 217,
        "championPointsUntilNextLevel": 6383,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 29,
        "championLevel": 2,
        "championPoints": 5139,
        "lastPlayTime": 1681150234000,
        "championPointsSinceLastLevel": 3339,
        "championPointsUntilNextLevel": 861,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 429,
        "championLevel": 2,
        "championPoints": 4382,
        "lastPlayTime": 1676117425000,
        "championPointsSinceLastLevel": 2582,
        "championPointsUntilNextLevel": 1618,
        "chestGranted": True,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 15,
        "championLevel": 2,
        "championPoints": 3704,
        "lastPlayTime": 1667296866000,
        "championPointsSinceLastLevel": 1904,
        "championPointsUntilNextLevel": 2296,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 21,
        "championLevel": 2,
        "championPoints": 3631,
        "lastPlayTime": 1662912065000,
        "championPointsSinceLastLevel": 1831,
        "championPointsUntilNextLevel": 2369,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 67,
        "championLevel": 2,
        "championPoints": 3224,
        "lastPlayTime": 1682355077000,
        "championPointsSinceLastLevel": 1424,
        "championPointsUntilNextLevel": 2776,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 22,
        "championLevel": 2,
        "championPoints": 2559,
        "lastPlayTime": 1676133704000,
        "championPointsSinceLastLevel": 759,
        "championPointsUntilNextLevel": 3441,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 7,
        "championLevel": 1,
        "championPoints": 1110,
        "lastPlayTime": 1685034736000,
        "championPointsSinceLastLevel": 1110,
        "championPointsUntilNextLevel": 690,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 63,
        "championLevel": 1,
        "championPoints": 1074,
        "lastPlayTime": 1595556490000,
        "championPointsSinceLastLevel": 1074,
        "championPointsUntilNextLevel": 726,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 23,
        "championLevel": 1,
        "championPoints": 975,
        "lastPlayTime": 1626241020000,
        "championPointsSinceLastLevel": 975,
        "championPointsUntilNextLevel": 825,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 30,
        "championLevel": 1,
        "championPoints": 201,
        "lastPlayTime": 1600591208000,
        "championPointsSinceLastLevel": 201,
        "championPointsUntilNextLevel": 1599,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 157,
        "championLevel": 1,
        "championPoints": 199,
        "lastPlayTime": 1678490332000,
        "championPointsSinceLastLevel": 199,
        "championPointsUntilNextLevel": 1601,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 235,
        "championLevel": 1,
        "championPoints": 175,
        "lastPlayTime": 1643177573000,
        "championPointsSinceLastLevel": 175,
        "championPointsUntilNextLevel": 1625,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 103,
        "championLevel": 1,
        "championPoints": 144,
        "lastPlayTime": 1649543078000,
        "championPointsSinceLastLevel": 144,
        "championPointsUntilNextLevel": 1656,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 24,
        "championLevel": 1,
        "championPoints": 143,
        "lastPlayTime": 1682448535000,
        "championPointsSinceLastLevel": 143,
        "championPointsUntilNextLevel": 1657,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
    {
        "puuid": "-kbxQ0spJBMGRZGy2fce97DBckHnpb5miceVkxbBP9HRhgevQhcuwNClRrGahgVKi3u-F3uOgX_RvA",
        "championId": 31,
        "championLevel": 1,
        "championPoints": 140,
        "lastPlayTime": 1682447045000,
        "championPointsSinceLastLevel": 140,
        "championPointsUntilNextLevel": 1660,
        "chestGranted": False,
        "tokensEarned": 0,
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
    },
]
