entry_miniseries_example = {
    "leagueId": "31a5c2c9-bd43-4aab-9841-282a3431fe29",
    "queueType": "RANKED_SOLO_5x5",
    "tier": "DIAMOND",
    "rank": "I",
    "summonerId": "JTv9359swD19EdkNFONC9bKI6bJ4fh5J3UjbJs7Gz9NsJaCO",
    "summonerName": "Vorxu",
    "leaguePoints": 100,
    "wins": 326,
    "losses": 282,
    "veteran": False,
    "inactive": False,
    "freshBlood": True,
    "hotStreak": False,
    "miniSeries": {"target": 2, "wins": 1, "losses": 1, "progress": "WLN"},
}
