entries_example = [
    {
        "leagueId": "28807304-53bf-485e-9255-333bd57a9e83",
        "queueType": "RANKED_FLEX_SR",
        "tier": "PLATINUM",
        "rank": "I",
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
        "summonerName": "GeneLL1",
        "leaguePoints": 3,
        "wins": 23,
        "losses": 17,
        "veteran": False,
        "inactive": False,
        "freshBlood": False,
        "hotStreak": False,
    },
    {
        "leagueId": "86cf4399-48fe-4ceb-898c-421320e42416",
        "queueType": "RANKED_SOLO_5x5",
        "tier": "DIAMOND",
        "rank": "I",
        "summonerId": "fyIndSpsUZToLTx9m0svW1J7UrsglQyw_C_A7w9gl9gCod9u",
        "summonerName": "GeneLL1",
        "leaguePoints": 0,
        "wins": 115,
        "losses": 105,
        "veteran": False,
        "inactive": False,
        "freshBlood": False,
        "hotStreak": False,
    },
]
