league_example = {
    "tier": "EMERALD",
    "leagueId": "15b4ec05-bd78-4d4b-8da2-ff68bd37c493",
    "queue": "RANKED_SOLO_5x5",
    "name": "Miss Fortune's Villains",
    "entries": [
        {
            "summonerId": "pPE4MoR7CkND99L38MPw9V1-CWT-PeXZzCxHDtcCxK9mz0U",
            "summonerName": "Ulltimatum",
            "leaguePoints": 35,
            "rank": "I",
            "wins": 157,
            "losses": 134,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "_bq69Vh8mC1EEwjhdRCmgnrI6fUCzL6M58yqw6J-rs-upQS8",
            "summonerName": "Naturâss",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 55,
            "losses": 42,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "KbeW9r9jIgzwA6L-ExlfX-LAvIIxb_9S5lTvb9PhrRIVQWU",
            "summonerName": "bitli piyade",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 94,
            "losses": 85,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "CKbn-hMHCFK9YbU0SDMTYGqRHHBomRQpQzHxF7BFL_giKxAn0l6a9ZlmRw",
            "summonerName": "PUNK NAVSEGDA",
            "leaguePoints": 24,
            "rank": "IV",
            "wins": 35,
            "losses": 32,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "3jItZWzORxOlgBPl9ydKO2n_KfqCrHe4Pyy4DlKd849T1a3f",
            "summonerName": "357MAGNUM GT900R",
            "leaguePoints": 63,
            "rank": "IV",
            "wins": 42,
            "losses": 36,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "5WgD2q67qdASnlWf5BAxThtzemTniIx5zjosV7SAaKKj7yc",
            "summonerName": "Lukko",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 78,
            "losses": 84,
            "veteran": False,
            "inactive": False,
            "freshBlood": True,
            "hotStreak": False
        },
        {
            "summonerId": "-OMWr9EsWTwBdVdYV-gB7NjqlSJ4Vr9MkUn5fRsm68M-UZzEdoUJ8awzXQ",
            "summonerName": "LylefRcE",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 10,
            "losses": 7,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "AU6FsaWbAxTCvSAKnrsDbgyxQBGgqcPYTPGlmnhd0V5D0yZg",
            "summonerName": "Sertiflex",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 109,
            "losses": 94,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "D9wRhs_qAUo_FnmoYW_CkhrOmD-aFNCCg5ehoqPnfDiD5GZ0fCCzPp1nLw",
            "summonerName": "MAamadaDiarra",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 162,
            "losses": 166,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "nt84h_EeAI1VKpJDBSSKiurwcXo2p8bq6jd7qzV2mwuBKcUlMWNmc97ghA",
            "summonerName": "holy bread",
            "leaguePoints": 55,
            "rank": "IV",
            "wins": 5,
            "losses": 4,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "1W_GoNt_voK7gaFwmwVcCp7UGmJtCHp5tia5Grb32BJLdRk",
            "summonerName": "legojpl",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 175,
            "losses": 172,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "ANCKCRng5ZHx4lqmQ843y0sNMgmnaqyE3MuYFHqVqtnYdoE",
            "summonerName": "Enoquilism",
            "leaguePoints": 11,
            "rank": "III",
            "wins": 86,
            "losses": 78,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "ZNB8puzu-6q017NMtxStnR-R_UjFSoJzJz7-_whzV8vPjD8",
            "summonerName": "Deadeγe",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 25,
            "losses": 21,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "MP80pXwiScp--Z0jkjS-0s2sy5gPRpIeTH60nLx6HeDdMa2D",
            "summonerName": "Musashi Kensei",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 58,
            "losses": 68,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "B9gY9EJIagYFPLS7feaINwndNgr7yhIzW6Mp2CkKjocGbHQWuOhJJCB_GA",
            "summonerName": "Catty Smurf",
            "leaguePoints": 33,
            "rank": "II",
            "wins": 57,
            "losses": 57,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "dMUFJcD0PHYnc3EjoFujJkK6dZ--YOUEZUT_V_vwbPZ-THidNYXoxknj_A",
            "summonerName": "Crushboy",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 40,
            "losses": 32,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "EBuiK_Vceiu6PocZXX2AQn6FUMAJ2gpz5oMmZGbvgS1TIoo",
            "summonerName": "I m B a L i",
            "leaguePoints": 14,
            "rank": "IV",
            "wins": 197,
            "losses": 188,
            "veteran": False,
            "inactive": False,
            "freshBlood": True,
            "hotStreak": False
        },
        {
            "summonerId": "efH1-DC_7OzKDjWayonom6CnYOgmwfaFDEYq3_oNi4P22bNn9bC8hufKZA",
            "summonerName": "Ganks Phobic",
            "leaguePoints": 31,
            "rank": "IV",
            "wins": 34,
            "losses": 23,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "NGe3GNwiX4A9_HnhyoYfCmoXwdYez0y64P7SRCdGNixb05Bf",
            "summonerName": "hurried player",
            "leaguePoints": 19,
            "rank": "III",
            "wins": 238,
            "losses": 220,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "f9T4IiDE1Fm-kGOiYsKS2tG00RlPm8tyfwJmI9yHs3lyZ-I",
            "summonerName": "Phinehasl",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 22,
            "losses": 22,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "5bS2VyJFXFkxSsijEG6h3v9AHtsj2kZll9PkD_m3tlDq32iW",
            "summonerName": "aryflex",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 22,
            "losses": 19,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "KSiXFi1KRx_oJqj-qv0tJk3ZHgzM3dU8RnXr7GDTRvj1bBo",
            "summonerName": "RNG INtent",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 15,
            "losses": 19,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "HZixjE7Qr_kQQxfeSydpCbdHZR9P1Kihs7IIvF-IErXLAGo2",
            "summonerName": "bwipu",
            "leaguePoints": 41,
            "rank": "IV",
            "wins": 4,
            "losses": 3,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "-TNMHWsYlnKFEZzraycTzqW8y-oVOCjLuFyDhPO3_lPGOkg",
            "summonerName": "Queen Zuw",
            "leaguePoints": 31,
            "rank": "III",
            "wins": 70,
            "losses": 67,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "pzqAIf3w2b_pTJvRMy4PisQDnepy1zGqWfsGVZtX7M1xnM0",
            "summonerName": "4sét",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 16,
            "losses": 14,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "3up-7IK94Wmu98qjz1dCKVVdUqSy7cvMiGkA2priSGQJGr4",
            "summonerName": "GumPeerS",
            "leaguePoints": 1,
            "rank": "II",
            "wins": 54,
            "losses": 48,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "bfLW-mDYn6kFXUBaNLgsV3VMIqXeBBT8WfhacU61HbdlDkM",
            "summonerName": "Shiikari",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 17,
            "losses": 11,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "RdTLOAfE9-Hp4VByTPxFxBfEp6DLEfweC7jWt8W_0qvnGhI",
            "summonerName": "Lord MistBörn",
            "leaguePoints": 25,
            "rank": "IV",
            "wins": 82,
            "losses": 80,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "mDULo8wNtppPGVjMgbEQj8pRL4v1F9TBBRb0qJN36MPq9FlvEfuNC1BRAQ",
            "summonerName": "Bosibitelae",
            "leaguePoints": 0,
            "rank": "II",
            "wins": 36,
            "losses": 33,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "C8gHCtvSS8K2P8EGqbQhucJ2yy5mWm6PZfQ4QHPzA26k9Z4",
            "summonerName": "Muac",
            "leaguePoints": 21,
            "rank": "III",
            "wins": 48,
            "losses": 43,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "wlY5vdpOGH9DIDO5_S685-Fb4rGnfJcANMxtq2TmJVL984E",
            "summonerName": "juanjito",
            "leaguePoints": 2,
            "rank": "II",
            "wins": 99,
            "losses": 76,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "cI8O1kacZfT2O25QMFh3LZEyMipif_5FzvM1Y6pVOfrwDTo",
            "summonerName": "2951725972",
            "leaguePoints": 71,
            "rank": "IV",
            "wins": 122,
            "losses": 104,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "uHW-KkhaipihGNb1wCLh9Kiux1T3hudm_Wff4NQO_yS9s6n83EpP5QyHwQ",
            "summonerName": "TheLastP1rate",
            "leaguePoints": 60,
            "rank": "II",
            "wins": 62,
            "losses": 48,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "3WN3uKEzAArThpZH4-9BKpCP_-0lAicSVRw4QQiSJU-j1EFl",
            "summonerName": "twø faced",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 141,
            "losses": 108,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "cd9wbKvcSkOiKl44kOuHjig_7qtb6z5LIAWdad75zJJRGLY",
            "summonerName": "KOKOSHANELL",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 105,
            "losses": 82,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "hblofXtmJeTB5R2CLVYz8QVMdmX322Y9d0GiZtgzQhfk0HzGWQBLYjMNHQ",
            "summonerName": "BrainRain",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 24,
            "losses": 30,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "b138z0EDOcgB8JoZRUWpWtGQkAsDdaOCjlm9nWzSSJfvfX5KFCseqUt-LQ",
            "summonerName": "Chop T0P",
            "leaguePoints": 10,
            "rank": "III",
            "wins": 48,
            "losses": 45,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "RYmKDa1jgBldMApWMAgUTdx2ACzQhPEsr9dtvIAcSWN1CU0",
            "summonerName": "Le Tusteur Fou",
            "leaguePoints": 47,
            "rank": "IV",
            "wins": 68,
            "losses": 44,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "B7ULeuLQjuEdRbMk9uj54murzoG-GXNBZj-17J7Dl28MVn0",
            "summonerName": "Twinbellows",
            "leaguePoints": 70,
            "rank": "IV",
            "wins": 38,
            "losses": 33,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "JC_wGrww0JjEQIvPEKlNoLgaeceprPtGhC0eneO4HlshZ502wIkN77QWkg",
            "summonerName": "Kenzie Cat",
            "leaguePoints": 18,
            "rank": "IV",
            "wins": 2,
            "losses": 5,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "cBVx4j5_IFKDZ1RBskDrmrFGnsr6QvdofHJ2hF_d0b5lclI",
            "summonerName": "Gol Dodger",
            "leaguePoints": 9,
            "rank": "III",
            "wins": 341,
            "losses": 328,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "ONlFE-0PZbfnP5HzN80LPLniwZ8ziAMfTCzpyfxm9_lf_fUIEA6wl2JVFA",
            "summonerName": "Call me Keanu",
            "leaguePoints": 45,
            "rank": "III",
            "wins": 163,
            "losses": 158,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "PSbnWhXLAJOLtG-FLNEIV9xP8Ylb-avLODqrOwulHb-BR-g",
            "summonerName": "Doming0 D RammuS",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 119,
            "losses": 135,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "8IX_bGvF8r464BLAV8ejy9FOzMGqYHjhLB9va2_SX_plJnc",
            "summonerName": "ŻagWøWW",
            "leaguePoints": 26,
            "rank": "IV",
            "wins": 94,
            "losses": 113,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "k6BD_p8bDYS4Vi53VZ-U5fm46F7SgcC7MTMw_ycwU369Qqc",
            "summonerName": "destructortotal9",
            "leaguePoints": 48,
            "rank": "IV",
            "wins": 238,
            "losses": 249,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "TVF4NKv3OXSxlzu--ikPAVmNax0QpbE-BvB8fJP08kvrB7Y",
            "summonerName": "J Black",
            "leaguePoints": 55,
            "rank": "IV",
            "wins": 27,
            "losses": 25,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "VNpi2VmzS1ZKC__XlakGs_6kQrsp5q1P59WuzamK8jYzrVpoZBFhWydr6A",
            "summonerName": "Viegonlyfans",
            "leaguePoints": 21,
            "rank": "IV",
            "wins": 70,
            "losses": 70,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "vnc6g-PJysIk2hYMU6usmvQHrCOKSgUvQrlCMYVcG-DhBMw",
            "summonerName": "yanying",
            "leaguePoints": 88,
            "rank": "IV",
            "wins": 16,
            "losses": 12,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "m7PUuzdJpFIeHi-90u4AbV8PR5_W-H4ZsvgVRwitqucVW__eyKWbqU8yHQ",
            "summonerName": "EDGviperbtw",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 31,
            "losses": 31,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "2ilzLmvuRX1iDp0udZ9QhtQF2z4pUpI6aW8JoIjVUZuvdgJy",
            "summonerName": "Abarame",
            "leaguePoints": 37,
            "rank": "III",
            "wins": 20,
            "losses": 15,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "zlXaMx_grTH2H1FTIxEMyexA6GJ7RuYSQ7bY-MuhocBhLtK8",
            "summonerName": "Ampoula",
            "leaguePoints": 75,
            "rank": "II",
            "wins": 138,
            "losses": 136,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "Qhj7xyjwbdyGIgCuhP_y_zHK7Gkqyr33LTP4B3T9U60Gjh1i",
            "summonerName": "UberWeed",
            "leaguePoints": 22,
            "rank": "IV",
            "wins": 75,
            "losses": 70,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "CToPwK7uVFxXO4kIH3oN5Dgh7T5QloncviN4Mf3WkVE3PKqv",
            "summonerName": "Trusted Jungle",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 92,
            "losses": 70,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "7gQrJuDWQYrsuM_Rw6pU4dbs4kKysT5rgluIeotqbhscUP0",
            "summonerName": "BORUTOS FATHER",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 35,
            "losses": 30,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "Iltk2NuEuIaGqajuxwjltukY0Z4vKpivAzcgHIUV6YokQfVcNfBCUZBo_g",
            "summonerName": "Homnageis",
            "leaguePoints": 22,
            "rank": "II",
            "wins": 37,
            "losses": 24,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "crcdASNFLkdO_vVfqR1ZQofvPFbs1j9Ik8KriiT0yiWEZinJ",
            "summonerName": "ShacoIsTrashBTW",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 69,
            "losses": 75,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "mkwPQ2YorRaJ3VfQJNYEOkXeL_vNgcP-fyS_q-wklqcT3j4",
            "summonerName": "Møwglee",
            "leaguePoints": 57,
            "rank": "IV",
            "wins": 15,
            "losses": 12,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "dFoQ0Cx4zy3HHWc-f2IzZqxf7eRP4KUYu6ApxMF00L211kc",
            "summonerName": "Abicrash",
            "leaguePoints": 26,
            "rank": "II",
            "wins": 36,
            "losses": 18,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "qQkDQNS-8SIoilJbbYYKVbk8TIRM8xtWB9ntg0euPtFez7fK",
            "summonerName": "ItsSinchel",
            "leaguePoints": 75,
            "rank": "IV",
            "wins": 22,
            "losses": 15,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "C-ymc8ppRX1QsljWy37VuGDJ8mKs40hnmKNMcCWvluPl7C4",
            "summonerName": "skillgrunt",
            "leaguePoints": 62,
            "rank": "II",
            "wins": 24,
            "losses": 29,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "OuRAmNn9rQI1jfTtFqaPkOujj2xnaKe7oz5hNSfLHS0OVTY",
            "summonerName": "Lloni activooooo",
            "leaguePoints": 75,
            "rank": "IV",
            "wins": 77,
            "losses": 68,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "51hNuRIvFoMXkGS4gcXQUzTLSChtMmVxg7gwRdbWygXHjX1YcXUalCTe1w",
            "summonerName": "Volcano1",
            "leaguePoints": 10,
            "rank": "III",
            "wins": 152,
            "losses": 155,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "q5G71GWqh9h7QJe8S6VPPWH8HxQ7Nwq2Gnokujw-pJb-9Eo",
            "summonerName": "riûken",
            "leaguePoints": 75,
            "rank": "IV",
            "wins": 110,
            "losses": 96,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "sOjXJs9_QaKK6VB8ypZ6bne79q4JQVjH4CqvbRTadd0SoVk",
            "summonerName": "Mible",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 60,
            "losses": 33,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "LhsCmx0G_-6pnMKrSP7Ye9BSKxwHw2vVcuaDgTnumZopwl0",
            "summonerName": "Money Pls Rito",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 42,
            "losses": 31,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "z_d9cQYyUZOuAof9zOGV6hSPJxPWHw5KzlE-Ju0CrgR64Wo",
            "summonerName": "Snelle Stefano",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 88,
            "losses": 82,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "BjCwDgMf6R-0x04lGkMuU9KlcoUKB-7ykvplRIx8nWM-2d-wCkJT6gObcg",
            "summonerName": "thetimemeow",
            "leaguePoints": 7,
            "rank": "IV",
            "wins": 62,
            "losses": 62,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "mYj8ImTEsH2gITVMPmYjqgS7HnRTsWn2FKz0VBUvAo4uqVE",
            "summonerName": "Vestation",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 84,
            "losses": 95,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "5n32ZUPYlpaPNa3zA1m_N8qt-cdQrdmNZkGJ_g6pmKe0RBgkD_k6PvMQYg",
            "summonerName": "MarkusekvDodavce",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 164,
            "losses": 168,
            "veteran": False,
            "inactive": False,
            "freshBlood": True,
            "hotStreak": False
        },
        {
            "summonerId": "vO7tdLyC_8eGJiRy73gK0z7YEi1Sak4NATm7XX5WDC6lCVeL",
            "summonerName": "Kaźuma",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 194,
            "losses": 194,
            "veteran": False,
            "inactive": False,
            "freshBlood": True,
            "hotStreak": True
        },
        {
            "summonerId": "YkO5z-UsC0SSDvLF3ZJu4_6PdS7o3l-CHpNhGWC3eDdvZjc",
            "summonerName": "Finndrake",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 33,
            "losses": 40,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "jhB_6dZqLgYLAZN2uN3GedqDhGear3QbG-Z1yHdcEo3SkXQ",
            "summonerName": "T1 Ryuu",
            "leaguePoints": 5,
            "rank": "III",
            "wins": 194,
            "losses": 210,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": True
        },
        {
            "summonerId": "8gI9bhgrms8mWDeraDece6gCUiwsz5xuCgnTQaEHGQ89ABY",
            "summonerName": "Kik00l0l",
            "leaguePoints": 25,
            "rank": "IV",
            "wins": 62,
            "losses": 66,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "8j6Kf4inb_wY_8eaHUddSeL3U8HUtejs23DDk1lWtBQ63WHKpw89ErLDBw",
            "summonerName": "OG Lifezoo",
            "leaguePoints": 38,
            "rank": "IV",
            "wins": 85,
            "losses": 88,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "DAnnNdM9rCM19KZNz64FLLH6S5VbPjGrH5e67gdxnlsDogmN",
            "summonerName": "Żaun RewinÐ",
            "leaguePoints": 0,
            "rank": "III",
            "wins": 285,
            "losses": 293,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "Ohob62t6Agax5G0sA4NzwI47PEKQqptMkyKAkmC6EudXdD8",
            "summonerName": "Kyoma",
            "leaguePoints": 75,
            "rank": "IV",
            "wins": 94,
            "losses": 95,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "DYibUKzkHHPxCwJ6ftykexJQpLxnOM4dT_hh7_d30W9kM1C0Adr_5eSAjg",
            "summonerName": "Milan Amstel",
            "leaguePoints": 0,
            "rank": "II",
            "wins": 21,
            "losses": 17,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "B37ovd7cHPwZHgp880l8xfLsIJud9ERCnuq7aMyXmvSSTr0",
            "summonerName": "DarthLordOfEvil",
            "leaguePoints": 19,
            "rank": "IV",
            "wins": 51,
            "losses": 56,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "GmrzDazS_aYqMvEg8ExGWK79lco2sEY2wi_95O8iuZDXKcQ",
            "summonerName": "davlaf",
            "leaguePoints": 24,
            "rank": "III",
            "wins": 167,
            "losses": 159,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "2fXqjOVfy8R-EZPV5-zaPRPVDDA2dD8PXBVoPZF47T8hJtc",
            "summonerName": "FishWrecker",
            "leaguePoints": 55,
            "rank": "IV",
            "wins": 39,
            "losses": 40,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "gxMXHshKZ5Yp1r3rkvlWgJFJZLHtDkiymvl1dJ2bVJvDsZz-",
            "summonerName": "aikoinaan",
            "leaguePoints": 0,
            "rank": "II",
            "wins": 130,
            "losses": 109,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "DHSYnzO8F49tOk9u3X1n-iN37db9X9vxaG2__5ajmBmY_z0X",
            "summonerName": "Zilean runner",
            "leaguePoints": 71,
            "rank": "III",
            "wins": 194,
            "losses": 180,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "7kcD6U1PSVuagv7NdlTS-gYzs6v9Xj9Vr5FIrSS4eadgiQY",
            "summonerName": "Exerit",
            "leaguePoints": 10,
            "rank": "IV",
            "wins": 17,
            "losses": 18,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "WAmNzq6xtE1z2y3LzYibbOc9phKd407_DTKTnof-fYOZArAe",
            "summonerName": "aoxyui",
            "leaguePoints": 66,
            "rank": "III",
            "wins": 20,
            "losses": 12,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "WWPy9bpDWJJq6dYF9Z6-4LaRpkuXnbHWZZgzntPVntktHG9aXGE4ubx_Tw",
            "summonerName": "Viskerino",
            "leaguePoints": 1,
            "rank": "IV",
            "wins": 99,
            "losses": 106,
            "veteran": False,
            "inactive": False,
            "freshBlood": True,
            "hotStreak": True
        },
        {
            "summonerId": "9l3GJAVqa4sHDo-Sbr8ygBd-GhqJHV6l8RN9lcRohvQjNL0x",
            "summonerName": "RITO MES RENAMES",
            "leaguePoints": 54,
            "rank": "III",
            "wins": 64,
            "losses": 66,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "7FwY5jLkzlYx1KF2sPXQ_R8IoJ8rqQre6YSi3c2aeHV7S2Fp",
            "summonerName": "alXmarkX",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 143,
            "losses": 144,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "V5fGwHbpWdtKFypotgs1s9nfDbWRVRFaPHmE9Dq8x8XjVew",
            "summonerName": "Nlklas",
            "leaguePoints": 0,
            "rank": "IV",
            "wins": 133,
            "losses": 127,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "S3fk-9FHyaaKu4glp5wHXeDQ9hOm2leJax9YkglwecXR39Q",
            "summonerName": "PrinzTilidin",
            "leaguePoints": 58,
            "rank": "IV",
            "wins": 65,
            "losses": 56,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "4SvXJ2n88aqVuZClaydQz9kCocfimhdVd2WVlLKsy2eyDEM",
            "summonerName": "nochapesbro",
            "leaguePoints": 11,
            "rank": "II",
            "wins": 61,
            "losses": 52,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "KKTZrgfGMKZ6g7GXe8dga5w7oLyiuggWEugsFoOIYAWzNIQkW1NUEV5Tww",
            "summonerName": "Oh pls",
            "leaguePoints": 1,
            "rank": "III",
            "wins": 63,
            "losses": 54,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "77FL1MvhkajVsoPDId3oOCXtbQp00GhQnkjYQSFayGKq_wo",
            "summonerName": "i am so iyi",
            "leaguePoints": 26,
            "rank": "I",
            "wins": 101,
            "losses": 72,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "4b6l1CYxEzQF7Tcvo5wO1JX4bw1G1PwR3XHF6j5Rqw0w0bg",
            "summonerName": "król komet",
            "leaguePoints": 24,
            "rank": "IV",
            "wins": 61,
            "losses": 49,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "XIuERSC_WHyZkutPwahZNsb38aM5QWWfCW5fuDJ6IrpfwnxPs7FWyYqgpg",
            "summonerName": "DOINB FAKER DPMN",
            "leaguePoints": 2,
            "rank": "IV",
            "wins": 31,
            "losses": 35,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "uzgAca-7_wPhcgIN48gtsBkNDpIlGJlVzdfJUYi8MeDF8Wft",
            "summonerName": "Alexmario02",
            "leaguePoints": 28,
            "rank": "IV",
            "wins": 37,
            "losses": 43,
            "veteran": False,
            "inactive": False,
            "freshBlood": True,
            "hotStreak": False
        },
        {
            "summonerId": "T7gq3cb0PqEiJJdhVxO-suz0ebSUsYPajQ6f0vYC9kc7ZU4G",
            "summonerName": "Mykickkills",
            "leaguePoints": 14,
            "rank": "II",
            "wins": 15,
            "losses": 15,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "OaaFTOGkkeONFRDw6zs4GUTIrQbUH5uEMQzQWRhREZ-K0L0",
            "summonerName": "gonzalox789",
            "leaguePoints": 59,
            "rank": "IV",
            "wins": 113,
            "losses": 88,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        },
        {
            "summonerId": "bPHHwyZoByez5Mrzm2IOs-hUlqwy_PnElc2P5kKN0HRzZY8",
            "summonerName": "Pabloguti1",
            "leaguePoints": 48,
            "rank": "IV",
            "wins": 48,
            "losses": 27,
            "veteran": False,
            "inactive": False,
            "freshBlood": False,
            "hotStreak": False
        }
    ]
}
